### ISSUE TITLE
The doubts of using

### ISSUE THREAD

**Issue by asgg4321** [SeanNaren/deepspeech.pytorch#174]
I would like to know about this project's applicability to Mandarin based on the deepspeech2 essay and whether it focuses on the applicability of speech recognition in English. Moreover, whether WER and CER follow the meanings in the thesis and represent the recognition error rate in Chinese and English, thank you

**Comment by SeanNaren** [comment]
For mandarin you only need CER (since its a character based language).
The tooling to train a model is here in this repo, however you would need to format your own data much like the datasets formatting scripts in the `data/` folder. Then using a custom set of labels you can train your own model!

The language model will be slightly more complicated since it doesn't have spaces, but you could always just start with greedy decoding before looking into character based lms.
