### ISSUE TITLE
Getting an error when using the option " --continue_from " 

### ISSUE THREAD

**Issue by saharghannay** [SeanNaren/deepspeech.pytorch#210]
Hi, 
I got this error when I tried to continue training from a check point (without doing fine tune).

TypeError: add_ received an invalid combination of arguments - got (int, torch.cuda.FloatTensor), but expected one of:
 * (float value)
 * (torch.FloatTensor other)
 * (torch.SparseFloatTensor other)
 * (float value, torch.FloatTensor other)
      didn't match because some of the arguments have invalid types: (int, torch.cuda.FloatTensor)
 * (float value, torch.SparseFloatTensor other)
      didn't match because some of the arguments have invalid types: (int, torch.cuda.FloatTensor)

Do you have an idea please how can I solve the problem ?
Thank you

**Comment by AMairesse** [comment]
This is an issue in pytorch (see https://github.com/pytorch/pytorch/issues/2830).
It was fixed with https://github.com/pytorch/pytorch/pull/3658 unfortunately it's not yet in the last release.

A workaround is to add :
```
if args.cuda:
    for state in optimizer.state.values():
        for k, v in state.items():
            if torch.is_tensor(v):
                state[k] = v.cuda()
```


after `optimizer.load_state_dict(package['optim_dict'])` on line 143 in train.py

**Comment by AMairesse** [comment]
#217 provided for temporary workaround

**Comment by saharghannay** [comment]
Thank you
