### ISSUE TITLE
Taking long time to process a single file during testng with LM

### ISSUE THREAD

**Issue by slbinilkumar** [SeanNaren/deepspeech.pytorch#340]
Hi,
Taking long time to process a single file during testng with LM. Size of LM is only 350 Mb. But still it takes a long time to predict the text output. Running in a GPU tesla K80 machine.

**Comment by slbinilkumar** [comment]
Utterance is around 15 seconds.beam size is 300 . Observed thing is loading
the LM it takes around 2 minutes to load.

**Comment by ryanleary** [comment]
It will take a while to load the language model into memory. Is it arpa or binary formatted? 

Are you saying it takes 2 minutes to process the utterance or 2 minutes from the start of the command to the script exiting?

**Comment by slbinilkumar** [comment]
It's binary format. 2 minutes to load the LM. I am planning to load LM
using pickle file.

**Comment by ryanleary** [comment]
So this isn't really an issue with this library nor the ctcdecode library. Loading the LM is just a slow operation. If you're going to need to run multiple utterances through, you should set up a server so that the acoustic model and language model can remain resident in memory and you can amortize the loading cost over all subsequent decode operations.

**Comment by slbinilkumar** [comment]
Thank you for your fast response.
