### ISSUE TITLE
Don't I need language model for training?

### ISSUE THREAD

**Issue by kouohhashi** [SeanNaren/deepspeech.pytorch#466]
Hi,
I have played Mozilla's DeepSpeech for a while and they (optionally) require language model for training. But I couldn't find any option for training model with language model here.

It seems language model is an option for inference only.
Is my understanding correct?

If so could someone explain why we need language model only for inference?

Anyway thank you for this great work.
I love pytorch more than tensorflow 1.x.

Thanks in advance.

**Comment by SeanNaren** [comment]
Hey @kouohhashi 

I'm not entirely sure why the language model is used in training, my guess is that it's only applied at validation time (inference).

The language model is only used at inference. It's used to help bias the decoding output towards words and is separately trained on a lot of text data (has nothing to do with audio). In general it helps gets more meaningful output from the model rather than disjointed letters.

Thanks for your kind words!

**Comment by kouohhashi** [comment]
@SeanNaren
Got it. 
Thanks a lot!
