### ISSUE TITLE
ctcdecode error

### ISSUE THREAD

**Issue by OmarHory** [SeanNaren/deepspeech.pytorch#580]
Hello, I tried to use an optional language model using beam but it doesn't work and results in this error.
![Screenshot from 2020-10-05 12-46-51](https://user-images.githubusercontent.com/43903002/95064805-eb13ac80-0708-11eb-963b-f53f4834e11c.png)

**Comment by OmarHory** [comment]
@SeanNaren I have still couldn't solve it, do you have any idea?

**Comment by kscheck** [comment]
I got the same error today and could debug it. It is caused by [`cutoff_top_n: float = 40 `](https://github.com/SeanNaren/deepspeech.pytorch/blob/193c0bfe4198dbf761d29350034f31fd77baac3e/deepspeech_pytorch/configs/inference_config.py#L13) in the LMConfig. `paddle_beam_decode_lm` requires an int value for this variable, but the config sets it to a float. So simply set it to `cutoff_top_n: int = 40 ` and that function should at least work.

**Comment by SeanNaren** [comment]
Thanks guys! @kscheck would you be able to make a PR to fix this?

**Comment by OmarHory** [comment]
@kscheck YOU ARE A LIFE-SAVER. THANKS!!!
