### ISSUE TITLE
Parameters and configuration for optimal model performance

### ISSUE THREAD

**Issue by mjurkus** [SeanNaren/deepspeech.pytorch#588]
I'm using your implementation, albeit adjusted a little, for Lithuanian language.

I could use some details on finding optimal configuration for the model. Currently, I'm using the default:
```
  hidden_size: 1024
  hidden_layers: 5
```
with bidirectional LSTM model, using half-precision.

Audio length varies between 3-30 seconds (don't know if that's OK)
Audio is studio quality recordings and conversational phone call recordings.

And since I don't have much audio (around 80hrs) I use `sox` augmentations to change pitch and speed.
```
        effects = [
            ['gain', '-n'],  # normalises to 0dB
            ['pitch', f"{pitch}"],  # pitch shift, valid rage -400..400
            ['speed', f'{speed:.2f}'],
            # ["echos", "0.8", "0.9", f"{int(self.rng.uniform(1, 100))}", "0.4"],
        ]
```

And if I apply any augmentation - model trains, but stops around WER 85%, CER 35%

But without any augmentation I can achieve better results, but it doesn't work well with unseen audio. For example phone call data, that was not seen be the model.

Any suggestions how to achieve better results?

**Comment by OmarHory** [comment]
I do not know if you still need help since this issue is stale.
Personally, I am training on Arabic Audio, I have not yet to face any difficulties with the all the default Model Architecture.
I would say if you can use less hidden units, say **512**, because the duration of your data isn't that long (which is still okay btw, there are applications where it detects a single word of 0.5sec length audio).

Regarding augmentation, there are three different ways as suggested by the README, 

1. **Spec Augment:** One of the better ones in my personal opinion, pretty much like random cuts in the spectrogram to make the model more robust to unseen noisy data
2. **Noise Injection:** (Is also great, but you must be aware that the given noise audio is distributed and variant (Not a single noise-audio-file that is only 10 seconds in length, look for _e.g.: 10 Hours Noise_ if that's available on the web.
3- **Speed volume perturb:** This is okay to use as well.

I would recommend trying out **Spec augment** at first.

The last thing I would suggest is to increase your training data, to make it more natural, which is the hardest part in my personal opinion, I have previously tried Deep Speech on 100 hours, and it was pretty much like a unigram language model :D 

I would suggest not augmenting the data before passing it to training. That would give the model to train on clear-well-heard data.
