### ISSUE TITLE
Regarding number of model parameters

### ISSUE THREAD

**Issue by samin9796** [SeanNaren/deepspeech.pytorch#608]
I have trained a model with 2 layers of 2D convolutions, followed by 7 recurrent layers with 768 hidden units and 1 fully connected layer. The model parameter is showed to be around 52 million in the log file. However, in the Deep Speech 2 paper by Baidu, they mentioned about 35 million parameters. I have worked with other network settings as well and every time model parameter in the log file seems to be much higher than it should be. Could you please clear up the confusion?

**Comment by SeanNaren** [comment]
It's because in the Baidu paper they tied the weights of the Bidirectional RNNs (the forward/backward weights are the same). Weight tying isn't supported and at this point where PyTorch has become far more advanced than the original paper (and so have GPUs) it isn't particularly worth tying the weights.

**Comment by samin9796** [comment]
@SeanNaren Thank you for your clarification. However, I am still struggling with calculating the number of parameters. Could you please give a rough calculation of why this is around 52 million? (2 layers of 2D convolutions, followed by 7 Bidirectional GRU layers with 768 hidden units and 1 fully connected layer provides 73 characters as output, other parameters are the default ones).
