### ISSUE TITLE
function augment_audio_with_sox  check

### ISSUE THREAD

**Issue by jeon30c** [SeanNaren/deepspeech.pytorch#72]
In dataloader.py
under func augment_audio_with_sox
I think
y = load_audio(path)
should be replaced to
y = load_audio(augmented_filename)

Am I right?
and do I have to post this kind of thing in the Issues? (I am newbie to github)

**Comment by SeanNaren** [comment]
Good catch thanks, I'll fix this myself!

What you could do (since this repo accepts pull requests) is create a [fork](https://help.github.com/articles/fork-a-repo/), clone that repo and make the change there. Then on github you can open a [pull request](https://help.github.com/articles/about-pull-requests/) from your fork to this repository with the change!

**Comment by SeanNaren** [comment]
Fixed in #73
