### ISSUE TITLE
Training deepspeech.pytorch with variable label size

### ISSUE THREAD

**Issue by Deepayan137** [SeanNaren/deepspeech.pytorch#99]
Hi,
    I am trying to implement text recognition using similar architecture and CTC loss. However, I am running into trouble since my label size is not constant. It depends on the size of the textual word for ex. 
 If I were to recognise the word **Sean** then my input image dimension will be **32XW**, W is the width of your word image, output dimension will be **W X number of classes** while label size will be **4**. Any suggestions as to how can I overcome this problem. Here number of classes represent the no. of alphabets in the lookup file.

**Comment by SeanNaren** [comment]
Bit difficult to grasp what you're actually doing, but the way we handle variable size outputs (which is one reason why CTC is used) is by adding lots of 'blank' labels. So we may have an output of size (29,100) but there are only 4 letters in the target! So what we would want the network to predict is basically a bunch of blank labels, then the 4 letters, then probably followed by more blank labels since it has to choose a label per time step. Hope that helps!
